/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portal;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lakshyadutt
 */
public class StaffRegistration extends javax.swing.JFrame {
    Connection conn;
    Statement stmt,stmt1;
    ResultSet rs,rs1;
    /**
     * Creates new form StaffRegistration
     */
    public StaffRegistration() {
        initComponents();
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/portal", "root", "");
            String course_query="SELECT * FROM combo";
            stmt=conn.createStatement();
            rs=stmt.executeQuery(course_query);
            while(rs.next()){
            courseCBX.addItem(rs.getString("courses"));
            if(rs.getString("gender").equals("")){
                
            }
            genderCBX.addItem(rs.getString("gender"));
            
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        genderLBL = new javax.swing.JLabel();
        mobileTF = new javax.swing.JTextField();
        mobileLBL = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        emailLBL = new javax.swing.JLabel();
        registerBTN = new javax.swing.JButton();
        titleLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        staffidTF = new javax.swing.JTextField();
        staffidLBL = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        passwordLBL = new javax.swing.JLabel();
        repasswordTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        courseCBX = new javax.swing.JComboBox<>();
        courseLBL = new javax.swing.JLabel();
        genderCBX = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        genderLBL.setText("Gender");

        mobileLBL.setText("Mobile");

        emailLBL.setText("EMail ID");

        registerBTN.setText("REGISTER");
        registerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTNActionPerformed(evt);
            }
        });

        titleLBL.setText("Student Registration Panel");

        nameLBL.setText("Name");

        staffidLBL.setText("Staff ID");

        passwordLBL.setText("Passsword");

        jLabel5.setText("Re-Enter");

        courseLBL.setText("Course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLBL)
                            .addComponent(passwordLBL)
                            .addComponent(courseLBL)
                            .addComponent(staffidLBL)
                            .addComponent(mobileLBL))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(courseCBX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(staffidTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(nameTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobileTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(repasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(genderLBL)
                                    .addGap(18, 18, 18)
                                    .addComponent(genderCBX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(titleLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(registerBTN)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffidLBL)
                    .addComponent(staffidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLBL)
                    .addComponent(jLabel5)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLBL)
                    .addComponent(courseCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLBL)
                    .addComponent(genderCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileLBL)
                    .addComponent(emailLBL)
                    .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerBTN)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void registerBTNActionPerformed(java.awt.event.ActionEvent evt) {                                            
        /*int flag = -1;
        String name =    nameTF.getText();
        String staffid = staffidTF.getText();
        String staff_password = passwordTF.getText();
        String mobile = mobileTF.getText();
        String emailID = emailTF.getText();
        String course = courseCBX.getSelectedItem().toString();
        String gender = genderCBX.getSelectedItem().toString();

        int answer = JOptionPane.showConfirmDialog(null, "Do You Want To Register?");
        if (answer == JOptionPane.YES_OPTION) {
            // Exception handling
            try {
                Class.forName("com.mysql.jdbc.Driver");
                //Statement statement = conn.createStatement();
                try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/portal", "root", ""); //Statement statement = conn.createStatement();
                        Statement statement = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
                    String query = "SELECT * FROM staff_users;";
                    String course_query="SELECT * FROM course";
                    ResultSet result1=statement.executeQuery(course_query);
                    String coursename=result1.getString("course_name");
                    try (ResultSet result = statement.executeQuery(query)) {
                        while (result.next()) {

                            String staffID = result.getString("staff_id");
                            if (staffid.equals(staffID)) {

                                JOptionPane.showMessageDialog(this, "User with this Staff ID Already Exists!");
                                staffidTF.setText("");
                                flag = 0;
                                break;
                            }
                        }

                        if (flag != 0) {
                            try (Statement statement1 = conn.createStatement()) {
                                String query1 = "INSERT INTO staff_users"
                                    + "(name,staff_id,password,email,mobile,course,gender) "
                                    + "VALUES('" + name + "'," + staffid + ",'" + staff_password +
                                    "','" + emailID + "'," + mobile + ",'" + course + "', '" + gender +"');";
                                statement1.executeUpdate(query1);
                                JOptionPane.showMessageDialog(null,"Registered Successfully");
                                StaffLogin sl=new StaffLogin();
                                sl.show();
                                this.dispose();
                            }
                        }
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                System.out.println(e);
            }
        }*/
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> courseCBX;
    private javax.swing.JLabel courseLBL;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JComboBox<String> genderCBX;
    private javax.swing.JLabel genderLBL;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mobileLBL;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton registerBTN;
    private javax.swing.JPasswordField repasswordTF;
    private javax.swing.JLabel staffidLBL;
    private javax.swing.JTextField staffidTF;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration                   
}

